//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public System.Guid Product_Id { get; set; }
        [Display(Name = "Product Name")]    //A data annotaion that indicates 'Product Name' will be displayed instead of 'Name' everytime the property is referenced
        public string Name { get; set; }
        [Display(Name = "Price of Product")]
        public decimal Price { get; set; }
    }
}
